variables:
  VERSION: 0.2.${CI_PIPELINE_ID}

stages:
  - release
  - deploy

upload-helm-chart:
  stage: release  
  image: alpine/k8s:1.22.6
  when: manual
  script:    
    - |
      sed -i "s/0.2.*/$VERSION/g" helm-charts/Chart.yaml
      if helm package ./helm-charts; then
        curl -v -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} ${NEXUS_HELM_URL} --upload-file $CI_PROJECT_DIR/momo-store-${VERSION}.tgz
      else
        echo "Failed to package Helm charts."
      fi


deploy-momo-store:
  stage: deploy
  image:
    name: alpine/k8s:1.24.13
  when: manual
  script:
    - kubectl config set-cluster "$KUBE_CLUSTER_NAME" --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials "$KUBE_USERNAME" --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster="$KUBE_CLUSTER_NAME" --user="$KUBE_USERNAME"
    - kubectl config use-context default
    - kubectl get po
    - helm repo add nexus ${NEXUS_HELM_URL} --username ${NEXUS_REPO_USER} --password ${NEXUS_REPO_PASS}
    - helm repo update
    - helm upgrade --install momo-store --atomic --timeout 15m nexus/momo-store