variables:
  VERSION: 0.2.${CI_PIPELINE_ID}

stages:
  - release
  - deploy

upload-helm-chart:
  stage: release  
  image: alpine/k8s:1.22.6
  when: manual
  script:    
    - |
      sed -i "s/0.2.*/$VERSION/g" helm-charts/Chart.yaml
      if helm package ./helm-charts; then
        curl -v -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} ${NEXUS_HELM_URL} --upload-file $CI_PROJECT_DIR/momo-store-${VERSION}.tgz
      else
        echo "Failed to package Helm charts."
      fi


deploy-production:
  stage: deploy
  image: dtzar/helm-kubectl  
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  script:
    - mkdir -p ~/.kube
    - ${KUBE_CONFIG} > ~/.kube/config
    - chmod 0600 ~/.kube/config
    - helm repo add nexus --username ${NEXUS_REPO_USER} --password ${NEXUS_REPO_PASS} $NEXUS_HELM_URL
    - helm repo update
    - >
      helm upgrade --install --atomic
      --kubeconfig ~/.kube/config
      --set frontend.fqdn=${FQDN_STORE}
      momo-store nexus/momo-store