variables:
  VERSION: 0.2.${CI_PIPELINE_ID}

stages:
  - release
  - deploy

upload-helm-chart:
  stage: release  
  image: alpine/k8s:1.22.6
  when: manual
  script:    
    - |
      sed -i "s/0.2.*/$VERSION/g" helm-charts/Chart.yaml
      if helm package ./helm-charts; then
        curl -v -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} ${NEXUS_HELM_URL} --upload-file $CI_PROJECT_DIR/momo-store-${VERSION}.tgz
      else
        echo "Failed to package Helm charts."
      fi


deploy-production:
  stage: deploy
  image: alpine:3.15.0
  when: manual
  before_script:
    - apk add openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - cat $KUBE_CONFIG > config
    - scp config ${USER}@${DEV_HOST}:/home/${USER}/.kube
    - |
      ssh -o "SendEnv LC_*" ${USER}@${DEV_HOST} /bin/bash -s << EOT
      kubectl config view --raw >~/.kube/config
      helm repo add nexus ${NEXUS_HELM_URL}
      helm repo update
      helm upgrade --install momo-store --atomic --timeout 15m nexus/momo-store
      rm ~/.kube/config 
      EOT